/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class MonsterTest {
  @Test
  public void monster() {
    Monster classUnderTest = new Monster("デュラハン", 0);
    assertEquals("デュラハン:レア度[0]", classUnderTest.toString());
  }

  @Test
  public void summonMonster() {
    Monster classUnderTest = new Monster("デュラハン", 0);
    assertEquals("ドラゴン", classUnderTest.summonMonster(2));
  }

  @Test
  public void dullahanText() {
    Monster classUnderTest = new Monster("デュラハン", 0);
    assertEquals("デュラハンは首なしの騎士で、恐ろしい姿をしているが、忠実な守護者でもある！", classUnderTest.dullahanText());
  }

  @Test
  public void golemText() {
    Monster classUnderTest = new Monster("ゴーレム", 1);
    assertEquals("ゴーレムは土から生み出された巨人で、頑丈な身体と怪力を武器に戦う", classUnderTest.golemText());
  }
}
