/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class MonsterTest {
  @Test
  public void monster() {
    Monster classUnderTest = new Monster("デュラハン", 0);
    assertEquals("デュラハン:レア度[0]", classUnderTest.toString());
  }

  @Test
  public void summonMonster() {
    Monster classUnderTest = new Monster("デュラハン", 0);
    assertEquals("ドラゴン", classUnderTest.summonMonster(2));
  }

  @Test
  public void dullahanText() {
    Monster classUnderTest = new Monster("デュラハン", 0);
    assertEquals("デュラハンは首なしの騎士で、恐ろしい姿をしているが、忠実な守護者でもある！", classUnderTest.dullahanText());
  }

  @Test
  public void golemText() {
    Monster classUnderTest = new Monster("ゴーレム", 1);
    assertEquals("ゴーレムは土から生み出された巨人で、頑丈な身体と怪力を武器に戦う", classUnderTest.golemText());
  }

  @Test
  public void dragonText() {
    Monster classUnderTest = new Monster("ドラゴン", 2);
    assertEquals("ドラゴンは天空を支配する伝説の生物で、巨大な翼と灼熱の炎で敵を圧倒する", classUnderTest.dragonText());
  }

  @Test
  public void phoenixText() {
    Monster classUnderTest = new Monster("フェニックス", 3);
    assertEquals("フェニックスは炎を纏った不死の鳥で、威厳に満ちた姿をしているが、希望と再生をもたらす慈愛の守護者でもある！", classUnderTest.phoenixText());
  }
}
