/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class MonsterTest {
  @Test
  public void monster() {
    Monster classUnderTest = new Monster("デュラハン", 0);
    assertEquals("デュラハン:レア度[0]", classUnderTest.toString());
  }

  @Test
  public void summonMonster() {
    Monster classUnderTest = new Monster("デュラハン", 0);
    assertEquals("ドラゴン", classUnderTest.summonMonster(2));
  }
}
